apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  namespace: wiz-exercise
spec:
  type: ClusterIP
  selector:
    app: tasky
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http

