apiVersion: v1
kind: Service
metadata:
  name: tina-service
  namespace: tina-ns
spec:
  type: ClusterIP
  selector:
    app: tasky
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http